### ISSUE TITLE
Getting error 'batch_noise' is not defined

### ISSUE THREAD

**Issue by erdalalim** [shivaverma/Face-Generator#1]
Hi, Iam tryning to run face_generator1.ipynb.. 
But Iam getting error on the last part of code,
ot these lines:

`loss_dis = sess.run(dis_loss, {input_noise: batch_noise, input_real: batch_images})
                   loss_gen = gen_loss.eval({input_real: batch_images, input_noise: batch_noise})`

**NameError: name 'batch_noise' is not defined**

I just change the path of my dataset like :

`image_ids=glob.glob('C://Users//userist//Desktop//casia//*')` 

and I run all the code without any change..

How can I fix this error?

**Comment by shivaverma** [comment]
Hi, 

This is because you are not able to read the images from that given location. You have to give the path to the folder that contains images. If you are able to read the images then `print(len(image_ids))` will print the number of images you have. Try changing your absolute path to relative path.

I have changed the name of the file to `face_generator_tf.ipynb`

**Comment by erdalalim** [comment]
@shivaverma thanks for feedback.
That given location contains just images there is no any subfolder inside. 
When I run `print(len(image_ids))` I get outpu that there is 35 images..
with absolute path..

I tried to give relative path like:
`image_ids=glob.glob('Desktop//casia//*')`
or changes like:
`image_ids=glob.glob('downloads//casia//*')`
`image_ids=glob.glob('..downloads//casia//*')`

when I run `print(len(image_ids))` in relative path I get output 0,which means there are no images inside folder..

are you sure that this error is because of the given location? Maybe any other suggestions?

**Comment by shivaverma** [comment]
Hi, 

I got what the problem is. Please look at the following code:

```python

batch_size = 128
epochs = 10
iters = len(image_ids)//batch_size     # look here
saver = tf.train.Saver(var_list = gen_vars)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    for e in range(epochs):
                
        for i in range(iters-1):   # you are not entering the loop
            
            batch_images = images[i*batch_size:(i+1)*batch_size]
            batch_noise = np.random.uniform(-1, 1, size=(batch_size, noise_size))
            
            sess.run(dis_opt, feed_dict={input_real: batch_images, input_noise: batch_noise})
            sess.run(gen_opt, feed_dict={input_real: batch_images, input_noise: batch_noise})

```
If you have 35 images, then you have to reduce the value of `batch_size` to less then 35, otherwise, the value of `iters` would be 0, and you will not enter the loop. And if you do not enter the loop then the value of `batch_noise` will not be initialized and you will get the error.

So to solve this problem you have to have images more than `batch_size`.

**Comment by erdalalim** [comment]
@shivaverma it sounds logical. But I change the `batch_size` to 34 and Iam getting still same error.

It looks like this:

`batch_size = 34
epochs = 10
iters = len(image_ids)//batch_size
saver = tf.train.Saver(var_list = gen_vars)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    for e in range(epochs):
                
        for i in range(iters-1):
            batch_images = images[i*batch_size:(i+1)*batch_size]
            batch_noise = np.random.uniform(-1, 1, size=(batch_size, noise_size))
            
            sess.run(dis_opt, feed_dict={input_real: batch_images, input_noise: batch_noise})
            sess.run(gen_opt, feed_dict={input_real: batch_images, input_noise: batch_noise})`


maybe I need some other changes?

**Comment by shivaverma** [comment]
Hi,

It should work if you are able to read the images. Print the value of `iters`, If it is greater than 0 then the error should not come. You can also put a print statement inside the loop to check if you are going there. Please let me know.

Also, you can put this `batch_noise = np.random.uniform(-1, 1, size=(batch_size, noise_size))` outside the loop where you are printing the loss, then error will not occur.
